version: '3'

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    hostname: api01
    environment:
      - DB_HOSTNAME=db

    ports:
      - '8081:8080'
    depends_on:
      - db

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - '8082:8080'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - '5432:5432'
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
